// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbinydkchjrfoxugybxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iaW55ZGtjaGpyZm94dWd5YnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzE0NjUsImV4cCI6MjA2MTAwNzQ2NX0.ji2DiMrr6B7b8AP8JNvW9aMgFSS0h1v-tttEomUuHug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);